# Generated by Django 5.0.6 on 2024-05-20 09:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(verbose_name='Сумма платежа')),
                ('donor_first_name', models.CharField(max_length=100, verbose_name='Имя плательщика')),
                ('donor_last_name', models.CharField(max_length=100, verbose_name='Фамилия плательщика')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('hide_amount', models.BooleanField(default=False, verbose_name='Скрыть сумму пожертвования')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collects.collect', verbose_name='Сбор')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
