# Generated by Django 5.0.6 on 2024-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Сумма платежа"
            ),
        ),
    ]
