# Generated by Django 5.0.6 on 2024-05-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запланированная сумма'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
    ]
